spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/default
    driver-class-name: com.mysql.cj.jdbc.Driver  #com.mysql.cj.jdbc.Driver  com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #druid配置详情信息
    name: druidDataSource
    max-active: 100  #最大连接数
    initial-size: 1  #初始化连接数
    max-wait: 60001  #获取最大等待时间
    min-idle: 1 #最小连接数
    validation-query: select 'x'  #
    time-between-eviction-runs-millis: 60000   #一个连接在池中最小生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 300000     #间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    pool-prepared-statements: false            #是否缓存preparedStatement 在mysql的环境下建议关闭 因为对数据库性能消耗大
    max-open-prepared-statements: 50
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat,wall
